### ISSUE TITLE
CirrusMD Proguard/Minify rules need updates

### ISSUE THREAD

**Issue by derekpitts28** [CirrusMD/CirrusMD-Android-SDK-Example#41]
Using the following build type for release results in the error at the bottom:

```
        release {
            signingConfig signingConfigs.release

            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled true
            useProguard true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
```

------------- ERROR -----------------------
`2021-06-16 13:33:17.004 12337-12337/? E/JodaTimeAndroid: Failed to retrieve identifier: type=class p.a.a.a.b name=joda_zoneinfomap
    java.lang.NoSuchFieldException: joda_zoneinfomap
        at java.lang.Class.getField(Class.java:1604)
        at p.a.a.a.c.b(ResUtils.java:7)
        at p.a.a.a.d.c(ResourceZoneInfoProvider.java:3)
        at p.a.a.a.d.<init>(ResourceZoneInfoProvider.java:3)
        at p.a.a.a.a.a(JodaTimeAndroid.java:3)
        at com.cirrusmd.androidsdk.CirrusMD.start(CirrusMD.kt:4)
        at f.h.a.a.onMethodCall(CirrusMdPlugin.kt:7)
        at j.a.e.a.i$a.a(MethodChannel.java:2)
        at j.a.d.b.e.b.b(DartMessenger.java:5)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-06-16 13:33:17.004 12337-12337/? E/MethodChannel#com.flutter.cirrus_md: Failed to handle method call
    java.lang.RuntimeException: Could not read ZoneInfoMap. You are probably using Proguard wrong.
        at p.a.a.a.a.a(JodaTimeAndroid.java:6)
        at com.cirrusmd.androidsdk.CirrusMD.start(CirrusMD.kt:4)
        at f.h.a.a.onMethodCall(CirrusMdPlugin.kt:7)
        at j.a.e.a.i$a.a(MethodChannel.java:2)
        at j.a.d.b.e.b.b(DartMessenger.java:5)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.io.IOException: Resource not found: "ZoneInfoMap" (resName: "joda_zoneinfomap")
        at p.a.a.a.d.c(ResourceZoneInfoProvider.java:5)
        at p.a.a.a.d.<init>(ResourceZoneInfoProvider.java:3)
        at p.a.a.a.a.a(JodaTimeAndroid.java:3)
        at com.cirrusmd.androidsdk.CirrusMD.start(CirrusMD.kt:4) 
        at f.h.a.a.onMethodCall(CirrusMdPlugin.kt:7) 
        at j.a.e.a.i$a.a(MethodChannel.java:2) 
        at j.a.d.b.e.b.b(DartMessenger.java:5) 
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:335) 
        at android.os.Looper.loop(Looper.java:183) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

------------- ERROR END -----------------------

Looks like you need to add this to your proguard file in your aar: 
https://github.com/dlew/joda-time-android/blob/main/library/proguard-rules.txt

**Comment by DanielGalarza** [comment]
@taylorjcase Looks like we got a Proguard issue here

**Comment by DanielGalarza** [comment]
@derekpitts28 Do you have any repro steps for this? I am running my example app, with the release configuration you mentioned above, but I don't see a crash anywhere.

**Comment by DanielGalarza** [comment]
We were able to confirm that adding these Proguard rules to the CirrusMD Android SDK, we were able to address this issue for Flutter projects:

```
# All the resources are retrieved via reflection, so we need to make sure we keep them
-keep class net.danlew.android.joda.R$raw { *; }

# These aren't necessary if including joda-convert, but
# most people aren't, so it's helpful to include it.
-dontwarn org.joda.convert.FromString
-dontwarn org.joda.convert.ToString

# Joda classes use the writeObject special method for Serializable, so
# if it's stripped, we'll run into NotSerializableExceptions.
# https://www.guardsquare.com/en/products/proguard/manual/examples#serializable
-keepnames class org.joda.** implements java.io.Serializable
-keepclassmembers class org.joda.** implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
```

**Comment by DanielGalarza** [comment]
Closing this issue since a hotfix has been release with version `9.0.1`
https://github.com/CirrusMD/CirrusMD-Android-SDK-Example/pull/44
